# Generated by Django 4.0 on 2022-01-21 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='status',
            field=models.CharField(choices=[('true', 'True'), ('false', 'False')], default='false', max_length=12),
        ),
    ]
