# Generated by Django 3.2.5 on 2021-07-06 06:08

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('bloc', '0002_auto_20210705_1541'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='slug',
            field=models.SlugField(default=uuid.uuid4, max_length=100, unique=True, verbose_name='Url'),
        ),
        migrations.AddField(
            model_name='eros',
            name='slug',
            field=models.SlugField(default=uuid.uuid4, max_length=100, unique=True, verbose_name='Url'),
        ),
    ]
