# Generated by Django 3.1 on 2021-07-06 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bloc', '0003_auto_20210706_1108'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hendrerit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('photo', models.ImageField(upload_to='media')),
                ('admin_name', models.CharField(max_length=25)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='opublikobana')),
                ('content', models.TextField()),
            ],
        ),
        migrations.AlterField(
            model_name='category',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='eros',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
