# Generated by Django 3.1 on 2021-07-06 11:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bloc', '0004_auto_20210706_1541'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Hendrerit',
            new_name='Post',
        ),
    ]
