# Generated by Django 3.1 on 2021-07-06 12:36

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('bloc', '0005_auto_20210706_1618'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='slug',
            field=models.SlugField(default=uuid.uuid4, max_length=255, unique=True, verbose_name='Url'),
        ),
    ]
