# Generated by Django 3.1 on 2021-07-08 07:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bloc', '0007_auto_20210708_1033'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Eros',
            new_name='Natoqne',
        ),
    ]
