# Generated by Django 4.0 on 2022-01-05 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bloc', '0007_alter_orderdetail_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='product/'),
        ),
    ]
