# Generated by Django 3.1 on 2021-07-10 11:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bloc', '0009_auto_20210710_1552'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='admin_name',
            new_name='user_name',
        ),
    ]
