# Generated by Django 3.1.7 on 2021-07-13 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bloc', '0011_valyuta'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='опубликовано'),
        ),
    ]
