# Generated by Django 4.0 on 2021-12-14 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bloc', '0014_auto_20211207_0121'),
    ]

    operations = [
        migrations.CreateModel(
            name='SendMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('email', models.EmailField(max_length=256)),
                ('phone_number', models.CharField(max_length=12)),
                ('message', models.TextField()),
            ],
        ),
        migrations.DeleteModel(
            name='Valyuta',
        ),
    ]
