# Generated by Django 4.0 on 2021-12-14 11:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bloc', '0015_sendmessage_delete_valyuta'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Natoqne',
            new_name='Jihozlar',
        ),
    ]
