# Generated by Django 4.0 on 2021-12-15 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bloc', '0016_rename_natoqne_jihozlar'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='price',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='jihozlar',
            name='description',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='jihozlar',
            name='price',
            field=models.IntegerField(default=0),
        ),
    ]
