# Generated by Django 4.0 on 2021-12-16 10:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bloc', '0017_category_price_jihozlar_description_jihozlar_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='Buy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.IntegerField()),
                ('number', models.IntegerField(default=1)),
                ('phone_number', models.CharField(max_length=12)),
                ('name', models.CharField(max_length=64)),
                ('title', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bloc.jihozlar')),
            ],
        ),
    ]
