# Generated by Django 4.0 on 2022-01-26 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RoleModuleConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('posts', models.BooleanField(default=True)),
                ('users', models.BooleanField(default=True)),
                ('role_name', models.CharField(max_length=255)),
            ],
        ),
        migrations.DeleteModel(
            name='Club',
        ),
    ]
